### ISSUE TITLE
CreateTeamAndSPO.ps1

### ISSUE THREAD

**Issue by joseabrams** [SmartterHealth/Virtual-Rounding#4]
When this command is executed

_"New-PnPList -Title $sublocationName -Url $sublocationshortName -Template GenericList"_

I received the following error and script ends

_"format-default : The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.
    + CategoryInfo          : NotSpecified: (:) [format-default], CollectionNotInitializedException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.CollectionNotInitializedException,Microsoft.PowerShell.Commands.FormatDefaultCommand"_

**Comment by maxafritz** [comment]
Resolved by Out-Null commandlets
